"use strict";
(() => {
  const TXT={
    de:{eyebrow:"P3DH · deutsche Referenzgruppe · Scale-out",title:"P3DH über mehrere Meldestichtage — Frameworkgrenzen und Missingness sichtbar",intro:"Diese Ebene erweitert den kontrollierten Pilot auf die eingefrorene deutsche Referenzgruppe. Werte stammen aus originalen EBA-XBRL-Report-Packages. Fehlende Meldungen an tatsächlich abgefragten Offenlegungsstichtagen werden als nicht beobachtet gezeigt, niemals als Null oder interpoliert. Perioden außerhalb des kennzahlenspezifischen Abfragefensters sind separat markiert. Die fünf Stichtage überqueren die Reporting-Framework-Grenze 4.1 → 4.2.",scope:"Referenzgruppe",dates:"Stichtage",source:"Original-XBRL als Wertquelle",qes:"QES nur Mapping + Crosscheck",noData:"Für dieses Institut liegt im kontrollierten P3DH-Umfang keine Zeitreihe vor.",caveat:"Vergleichbar mit Hinweis",break:"Methodischer Reihenbruch",missing:"Keine Meldung beobachtet",framework:"RF",historical:"TE-Referenz 30.06.2025",audit:"Prüfebene",basis:"Leverage-Basis",datapoint:"Datapoint",variable:"VariableID",cell:"Zelle",package:"Report Package",csv:"Original-CSV",hash:"SHA-256",formula:"Ableitung",performing:"Performing",nonperforming:"Non-performing",freshness:"Freshness",freshnessContext:"Freshness-Kontext",observed:"vorhanden",gaps:"fehlend",cadenceNA:"nicht im Abfragefenster",legend:"Diskrete Punkte statt Trendlinie: Es wird keine methodische Kontinuität unterstellt.",boundary:"Frameworkwechsel"},
    en:{eyebrow:"P3DH · German reference group · scale-out",title:"P3DH across multiple reporting dates — framework boundaries and missingness kept visible",intro:"This layer expands the controlled pilot to the frozen German reference group. Values come from original EBA XBRL report packages. A missing disclosure at a date actually queried for that metric is shown as not observed; it is never rendered as zero or interpolated. Periods outside the metric-specific query cadence are marked separately. The five dates cross the Reporting Framework 4.1 → 4.2 boundary.",scope:"Reference group",dates:"Dates",source:"Original XBRL as value source",qes:"QES for mapping + cross-check only",noData:"No P3DH time series is available for this institution in the controlled P3DH scope.",caveat:"Comparable with caveat",break:"Series break",missing:"No disclosure observed",framework:"RF",historical:"TE reference 30 Jun 2025",audit:"Audit view",basis:"Leverage basis",datapoint:"Datapoint",variable:"VariableID",cell:"Cell",package:"Report package",csv:"Original CSV",hash:"SHA-256",formula:"Derivation",performing:"Performing",nonperforming:"Non-performing",freshness:"Freshness",freshnessContext:"Freshness context",observed:"available",gaps:"missing",cadenceNA:"outside query cadence",legend:"Discrete points rather than a trend line: no methodological continuity is assumed.",boundary:"Framework change"}
  };
  let data=null,historical=null;
  const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const lang=()=>document.documentElement.lang==="en"?"en":"de"; const t=k=>TXT[lang()][k]||k;
  const num=v=>(v===null||v===undefined||v==="")?null:Number(v);
  const pct=v=>num(v)===null?"—":new Intl.NumberFormat(lang()==="de"?"de-DE":"en-GB",{minimumFractionDigits:2,maximumFractionDigits:2}).format(num(v)*100)+" %";
  const dateLabel=s=>{const d=new Date(s+"T00:00:00Z");return new Intl.DateTimeFormat(lang()==="de"?"de-DE":"en-GB",{day:"2-digit",month:"2-digit",year:"numeric",timeZone:"UTC"}).format(d)};
  const metricName=m=>({de:{CET1:"CET1-Quote",LEVERAGE:"Leverage Ratio",NPL:"NPL-Quote"},en:{CET1:"CET1 ratio",LEVERAGE:"Leverage ratio",NPL:"NPL ratio"}})[lang()][m]||m;
  const histMetric=m=>({CET1:"EBA_CET1_RATIO_TRANSITIONAL",LEVERAGE:"EBA_LEVERAGE_RATIO_TRANSITIONAL",NPL:"EBA_NPL_RATIO_DERIVED_TE2025"})[m];
  const selectedLei=()=>document.querySelector("#bankSelect")?.value||"";
  const histValue=(lei,m)=>historical?.find(x=>x.lei===lei&&x.metric_id===histMetric(m)&&x.reference_date==="2025-06-30")?.numeric_value??null;
  const modeLabel=m=>m==="SERIES_BREAK_REQUIRED"?t("break"):t("caveat"); const modeClass=m=>m==="SERIES_BREAK_REQUIRED"?"series-break":"with-caveat";
  const byKey=recs=>new Map(recs.map(r=>[r.reference_date,r]));
  const seedForMetric=m=>({CET1:"KM1",LEVERAGE:"LR2",NPL:"CR1"})[m];
  const isScheduled=(m,d)=>(data.query_schedule_by_seed?.[seedForMetric(m)]||[]).includes(d);
  function detail(r){
    const d=document.querySelector("#detailDialog"),c=document.querySelector("#detailContent");if(!d||!c)return;
    const rows=[["Metric",r.metric_id],[t("source"),r.production_value_source],[t("qes"),r.qes_role],[t("framework"),`${r.framework} · source-native FrameworkID ${r.source_native_framework_id??"—"}`],[t("freshness"),r.freshness_status],[t("freshnessContext"),`${r.freshness_context_latest_reference_date??"—"} · ${r.freshness_reason_code??"—"}`],["Assertion",r.assertion_level],["Evidence",r.evidence_level],[modeLabel(r.comparison_mode),r.comparison_reason]];
    if(r.metric!=="NPL"){rows.splice(3,0,[t("cell"),r.source_cell_code],[t("variable"),r.variable_id],[t("datapoint"),r.source_datapoint]);if(r.metric==="LEVERAGE")rows.push([t("basis"),`${r.leverage_basis_label||"—"} · ${r.leverage_basis_code||"—"}`]);}
    else{rows.splice(3,0,[t("formula"),"NPE / (performing + NPE)"],[t("performing"),`${r.performing_cell_code} · VariableID ${r.performing_variable_id} · ${r.performing_datapoint} · ${r.performing_value}`],[t("nonperforming"),`${r.nonperforming_cell_code} · VariableID ${r.nonperforming_variable_id} · ${r.nonperforming_datapoint} · ${r.nonperforming_value}`]);}
    rows.push([t("package"),r.source_zip],[t("csv"),r.source_csv],[t("hash"),r.source_zip_sha256]); const link=r.official_url?`<p><a href="${esc(r.official_url)}" target="_blank" rel="noopener noreferrer">EBA ↗</a></p>`:"";
    c.innerHTML=`<div class="eyebrow">${esc(t("audit"))}</div><h2>${esc(metricName(r.metric))} · ${esc(dateLabel(r.reference_date))} · ${esc(pct(r.value))}</h2><dl class="prov">${rows.map(([a,b])=>`<dt>${esc(a)}</dt><dd>${esc(b??"—")}</dd>`).join("")}</dl>${link}`;d.showModal();
  }
  function periodCell(date,r,metric){const fw=data.framework_by_date[date];if(!r&&!isScheduled(metric,date))return `<div class="p3dh-period not-scheduled" data-date="${esc(date)}" data-framework="${esc(fw)}"><small>${esc(dateLabel(date))}</small><strong>—</strong><span>${esc(t("cadenceNA"))}</span><em>${esc(t("framework"))} ${esc(fw)}</em></div>`;if(!r)return `<div class="p3dh-period missing" data-date="${esc(date)}" data-framework="${esc(fw)}"><small>${esc(dateLabel(date))}</small><strong>—</strong><span>${esc(t("missing"))}</span><em>${esc(t("framework"))} ${esc(fw)}</em></div>`;return `<button type="button" class="p3dh-period observed ${modeClass(r.comparison_mode)}" data-date="${esc(date)}" data-framework="${esc(fw)}" data-comparison-mode="${esc(r.comparison_mode)}"><small>${esc(dateLabel(date))}</small><strong>${esc(pct(r.value))}</strong><span>${esc(modeLabel(r.comparison_mode))}</span><em>${esc(t("framework"))} ${esc(fw)}</em></button>`;}
  function metricCard(lei,metric,recs){const map=byKey(recs),dates=data.target_reference_dates,eligible=dates.filter(d=>isScheduled(metric,d)),present=eligible.filter(d=>map.has(d)).length,missing=eligible.length-present,na=dates.length-eligible.length,hv=histValue(lei,metric),cells=dates.map(d=>periodCell(d,map.get(d),metric));const bi=dates.findIndex(d=>data.framework_by_date[d]==="4.2");if(bi>0)cells.splice(bi,0,`<div class="p3dh-framework-boundary" aria-label="${esc(t("boundary"))}"><span>4.1</span><i>→</i><span>4.2</span></div>`);return `<article class="p3dh-scale-card" data-metric="${esc(metric)}"><div class="p3dh-card-head"><div><span class="kind">${esc(metricName(metric))}</span><h3>${esc(metricName(metric))}</h3></div><span class="coverage-chip">${present} ${esc(t("observed"))} · ${missing} ${esc(t("gaps"))}${na?` · ${na} ${esc(t("cadenceNA"))}`:""}</span></div><div class="p3dh-historical-reference"><small>${esc(t("historical"))}</small><strong>${esc(pct(hv))}</strong></div><div class="p3dh-period-strip">${cells.join("")}</div><p class="comparison-copy">${esc(t("legend"))}</p></article>`;}
  function render(){if(!data)return;const section=document.querySelector("#p3dhBridgeSection"),panel=document.querySelector("#p3dhBridgePanel");if(!section||!panel)return;const lei=selectedLei(),recs=data.records.filter(r=>r.lei===lei),metrics=["CET1","LEVERAGE","NPL"];section.querySelector("[data-p3dh-eyebrow]").textContent=t("eyebrow");section.querySelector("[data-p3dh-title]").textContent=t("title");section.querySelector("[data-p3dh-intro]").textContent=t("intro");section.querySelector("[data-p3dh-meta]").innerHTML=`<span>${esc(t("scope"))}: <strong>${data.institution_count}</strong></span><span>${esc(t("dates"))}: <strong>${data.target_reference_dates.length}</strong></span><span>${esc(t("source"))}</span><span>${esc(t("qes"))}</span>`;section.querySelector("[data-p3dh-legend]").innerHTML=`<span>RF 4.1: ${esc(dateLabel("2025-06-30"))}–${esc(dateLabel("2025-12-31"))}</span><span>RF 4.2: ${esc(dateLabel("2026-03-31"))}–${esc(dateLabel("2026-06-30"))}</span>`;if(!recs.length){panel.innerHTML=`<div class="card panel p3dh-empty">${esc(t("noData"))}</div>`;return;}panel.innerHTML=metrics.map(m=>metricCard(lei,m,recs.filter(r=>r.metric===m))).join("");panel.querySelectorAll("button.p3dh-period.observed").forEach(btn=>btn.addEventListener("click",()=>{const r=recs.find(x=>x.reference_date===btn.dataset.date&&x.metric===btn.closest('.p3dh-scale-card').dataset.metric);if(r)detail(r);}));}
  async function init(){try{const[b,h]=await Promise.all([fetch("data/14_p3dh_current_bridge.json",{cache:"no-store"}),fetch("data/03_headline_observations.json",{cache:"no-store"})]);if(!b.ok||!h.ok)throw new Error(`P3DH scale-out load failed ${b.status}/${h.status}`);data=await b.json();historical=await h.json();window.__ebaBuild09Scaleout=data;const wait=()=>{const sel=document.querySelector("#bankSelect"),lb=document.querySelector("#langButton");if(!sel||!lb||!sel.options.length){setTimeout(wait,40);return;}sel.addEventListener("change",()=>setTimeout(render,0));lb.addEventListener("click",()=>setTimeout(render,0));new MutationObserver(()=>render()).observe(document.documentElement,{attributes:true,attributeFilter:["lang"]});render();};wait();}catch(e){console.error("Build09 scale-out",e);const p=document.querySelector("#p3dhBridgePanel");if(p)p.innerHTML=`<div class="error">P3DH scale-out load failed: ${esc(e.message)}</div>`;}}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();
