const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':'&quot;',"'":"&#39;"}[m]));
const fmt=n=>n==null?'—':new Intl.NumberFormat(document.documentElement.lang==='en'?'en-GB':'de-DE',{maximumFractionDigits:2}).format(Number(n));
const state={lang:'de',snapshot:null,entityMap:new Map(),metricMap:new Map(),sourceMap:new Map(),runtime:window.FI2A_PUBLIC_SNAPSHOT?'static':'local'};
const I18N={
de:{
heroKicker:'Quellengebundene Finanz- und Versicherungsanalyse',heroTitle:'Von der Quelle zur prüfbaren Analyse.',
heroText:'Banken und Versicherungen in einer gemeinsamen, semantisch kontrollierten Anwendung. Fakten, Vergleichbarkeit, historische Entwicklung, Abhängigkeiten, explorative Kandidaten und Auditpfade bleiben getrennt und nachvollziehbar.',
introKicker:'KURZ ERKLÄRT',introTitle:'Worum es hier geht',
introP1:'Finance/Insurance2Agent ist ein privates, unabhängiges Analyse- und Informationswerkzeug für öffentlich zugängliche Finanz- und Versicherungsdaten. Es ist weder eine Veröffentlichung einer Aufsichtsbehörde noch der dargestellten Unternehmen und bietet keine Anlage-, Versicherungs- oder Rechtsberatung. Die aktuelle öffentliche Fassung umfasst 140 Institutionen, 100 Kennzahldefinitionen und 7.207 kanonische Beobachtungen aus 167 Quelldokumenten. Bei Versicherungsdaten lassen sich unter anderem gemeldete Solvency-II-Quoten, zugrunde liegende Eigenmittel (EOF) und Solvenzkapitalanforderungen (SCR) bis zur Quelle nachvollziehen; bei Bankdaten reichen die Evidenzpfade bis zu EBA-Datapoints, Perioden und Quellendokumenten.',
introP2:'Gemeldete Werte und Komponenten werden aus veröffentlichten Unternehmens- und Aufsichtsquellen übernommen. Wo die App selbst eine Größe berechnet oder transformiert – etwa eine rekonstruierte Quote 100 × EOF / SCR, eine abgeleitete Bankkennzahl oder eine zulässige Statistik – wird dies als abgeleitete beziehungsweise statistische Größe kenntlich gemacht. Solche Rechengrößen werden nicht mit berichteten SOURCE_FACT-Werten gleichgesetzt.',
introP3:'Ebenso wichtig wie die Zahl selbst ist ihre Vergleichbarkeit. Gleich benannte Kennzahlen können auf unterschiedlichen Regimen, internen Modellen, Übergangsmaßnahmen, Konsolidierungsebenen oder Bewertungsannahmen beruhen. Vor Paar- und Kohortenvergleichen prüft die App deshalb die dokumentierte Semantik und Abhängigkeiten. Ist ein Vergleich nur näherungsweise möglich, zeigt sie die Unterschiede; ist die Grundlage ungelöst oder nicht vergleichbar, wird unzulässige Arithmetik zurückgehalten. Rankings bleiben geschlossen; Kohortenstatistiken werden nur freigegeben, wenn die dafür definierten Vergleichbarkeits- und Abhängigkeitsregeln erfüllt sind. Ungeklärte Semantik wird nicht durch automatische Normalisierung wegdefiniert.',
introLink:'Methodik und Evidenzmodell im Detail',
tabAsk:'ABFRAGEN',tabCompare:'VERGLEICHEN',tabInvestigate:'UNTERSUCHEN',tabDiscover:'ENTDECKEN',tabAudit:'PRÜFEN',
askTitle:'Institutionen, Fakten und Evidenzsuche',askHelp:'Strukturierte Abfrage, Institutionen-Browser und freie deterministische Evidenzsuche direkt aus dem kanonischen Bestand.',
structuredQuery:'Strukturierte Abfrage',freeEvidence:'Freie Evidenzsuche',searchTerms:'Suchbegriffe',search:'Suchen',institutionBrowser:'Institutionen-Browser',filter:'Filter',type:'Typ',country:'Land',
institution:'Institution',metric:'Kennzahl',show:'Anzeigen',compareTitle:'Vergleichbarkeit vor Arithmetik',compareHelp:'Paar- und Kohortenvergleich mit Regime-, Semantik- und Abhängigkeitsprüfung. Rankings bleiben geschlossen.',
institutionA:'Institution A',institutionB:'Institution B',compare:'Vergleichen',cohort:'Kohorte (mehrere auswählen)',checkCohort:'Kohorte prüfen',
investigateTitle:'Dossier, Zeitreihe, Komponenten, Quellen und Abhängigkeiten',investigateHelp:'Historische Entwicklung, Metric-/Component-Explorer, Source Browser, Ownership/Dependency Graph und semantische Übergänge in einer Ansicht.',
investigate:'Untersuchen',discoverTitle:'Deterministische Kandidaten und Threads',discoverHelp:'Explorative Kandidaten und Investigation Threads. Keine stille Beförderung zu Fakten oder Hypothesen.',
institutionOptional:'Institution (optional)',showCandidates:'Kandidaten anzeigen',auditTitle:'Vom Ergebnis zurück zur Quelle',auditHelp:'Observation → Entity → Metric → Semantic Profile → Source → Lineage → Time-Series-Entscheidung → Evidence Graph.',
observationId:'Observation ID',trace:'Trace',rerun:'Neu berechnen',methodology:'Methodik',aiTransparency:'KI-Transparenz',privacy:'Datenschutz',imprint:'Impressum',
agentOrchestrator:'Lokale Agent-Orchestrierung',agentHelp:'Typisierte, deterministische Agenten. Eine optionale lokale LLM-Synthese ist nur über Loopback zulässig und niemals kanonisch.',question:'Frage / Auftrag',route:'Routen',
noFact:'Kein kanonischer Fakt für diese Auswahl.',noResults:'Keine Treffer.',enterSearch:'Bitte Suchbegriff eingeben.',notRecorded:'nicht erfasst',pageLocator:'Seitenlocator',tableLocator:'Tabelle',datapointLocator:'Datapoint',locatorNotRecorded:'Quellenlocator nicht erfasst',auditButton:'Prüfen',autonomousGateHelp:'AUTONOMOUS_LLM_HYPOTHESIS = CLOSED ist bewusst gesetzt: Die öffentliche App nutzt deterministische Discovery-Kandidaten, erzeugt aber noch keine autonomen LLM-Hypothesen. Das ist ein Methoden-Gate, kein Fehler.',facts:'Fakten',sources:'Quellen',relations:'Relationen',regimes:'Regime',periods:'Perioden',coverage:'Abdeckung',
releaseGates:'Release-/Methoden-Gates',runtime:'Laufzeit',static:'STATISCH',local:'LOKAL',statisticsAuthorized:'STATISTIK FREIGEGEBEN',statisticsWithheld:'STATISTIK ZURÜCKGEHALTEN',rankingClosed:'RANKING GESCHLOSSEN',
timeSeries:'Zeitreihe',ownership:'Ownership / Dependency',components:'Komponenten / Kennzahlenfamilien',metricExplorer:'Metrik-Explorer',sourceBrowser:'Source Browser',officialSource:'Offizielle Quelle',
candidates:'Kandidaten',threads:'Investigation Threads',evidenceGraph:'Evidence Graph',source:'Quelle',entity:'Entity',semantic:'Semantik',lineage:'Lineage',decisions:'Zeitreihen-Entscheidungen',
implemented:'Tatsächlich implementierte Funktionen',publicStatic:'Öffentlich statisch',localFull:'Lokal vollständig'
},
en:{
heroKicker:'Source-bound finance and insurance analysis',heroTitle:'From source to auditable analysis.',
heroText:'Banks and insurers in one semantically controlled application. Facts, comparability, historical development, dependencies, exploratory candidates and audit paths remain separated and traceable.',
introKicker:'QUICK GUIDE',introTitle:'What this app does',
introP1:'Finance/Insurance2Agent is a private, independent analysis and information tool for publicly available finance and insurance data. It is neither a publication by a supervisory authority nor by the companies shown, and it does not provide investment, insurance or legal advice. The current public edition contains 140 institutions, 100 metric definitions and 7,207 canonical observations from 167 source documents. For insurance data, users can trace items such as reported Solvency II ratios, underlying Eligible Own Funds (EOF) and Solvency Capital Requirements (SCR) back to their sources; for banking data, evidence paths extend to EBA datapoints, periods and source documents.',
introP2:'Reported values and components are taken from published company and supervisory sources. Where the app calculates or transforms a value itself – for example a reconstructed 100 × EOF / SCR ratio, a derived banking metric or an authorized statistic – it is explicitly marked as a derived or statistical value. Such calculations are not presented as reported SOURCE_FACT values.',
introP3:'Comparability matters as much as the number itself. Identically named metrics can rest on different regimes, internal models, transitional measures, consolidation scopes or valuation assumptions. Before pair or cohort comparisons, the app therefore checks documented semantics and dependencies. If comparability is only approximate, it shows the gaps; if the basis is unresolved or not comparable, unsupported arithmetic is withheld. Rankings remain closed; cohort statistics are released only when the defined comparability and dependency rules are satisfied. Unresolved semantics are not erased by automatic normalization.',
introLink:'Methodology and evidence model in detail',
tabAsk:'ASK',tabCompare:'COMPARE',tabInvestigate:'INVESTIGATE',tabDiscover:'DISCOVER',tabAudit:'AUDIT',
askTitle:'Institutions, facts and evidence search',askHelp:'Structured query, institution browser and deterministic free evidence search directly over the canonical evidence core.',
structuredQuery:'Structured query',freeEvidence:'Free evidence search',searchTerms:'Search terms',search:'Search',institutionBrowser:'Institution browser',filter:'Filter',type:'Type',country:'Country',
institution:'Institution',metric:'Metric',show:'Show',compareTitle:'Comparability before arithmetic',compareHelp:'Pair and cohort comparison with regime, semantic and dependency checks. Rankings remain closed.',
institutionA:'Institution A',institutionB:'Institution B',compare:'Compare',cohort:'Cohort (select several)',checkCohort:'Check cohort',
investigateTitle:'Dossier, time series, components, sources and dependencies',investigateHelp:'Historical development, metric/component explorer, source browser, ownership/dependency graph and semantic transitions in one view.',
investigate:'Investigate',discoverTitle:'Deterministic candidates and threads',discoverHelp:'Exploratory candidates and investigation threads. No silent promotion to facts or hypotheses.',
institutionOptional:'Institution (optional)',showCandidates:'Show candidates',auditTitle:'Trace a result back to evidence',auditHelp:'Observation → Entity → Metric → Semantic Profile → Source → Lineage → time-series decision → evidence graph.',
observationId:'Observation ID',trace:'Trace',rerun:'Rerun',methodology:'Methodology',aiTransparency:'AI transparency',privacy:'Privacy',imprint:'Imprint',
agentOrchestrator:'Local agent orchestration',agentHelp:'Typed deterministic agents. Optional local-LLM synthesis is loopback-only and never canonical.',question:'Question / task',route:'Route',
noFact:'No canonical fact for this selection.',noResults:'No results.',enterSearch:'Enter a search term.',notRecorded:'not recorded',pageLocator:'Page locator',tableLocator:'Table',datapointLocator:'Datapoint',locatorNotRecorded:'Source locator not recorded',auditButton:'Audit',autonomousGateHelp:'AUTONOMOUS_LLM_HYPOTHESIS = CLOSED is intentional: the public app uses deterministic discovery candidates but does not yet generate autonomous LLM hypotheses. This is a methodology gate, not an error.',facts:'Facts',sources:'Sources',relations:'Relations',regimes:'Regimes',periods:'Periods',coverage:'Coverage',
releaseGates:'Release / method gates',runtime:'Runtime',static:'STATIC',local:'LOCAL',statisticsAuthorized:'STATISTICS AUTHORIZED',statisticsWithheld:'STATISTICS WITHHELD',rankingClosed:'RANKING CLOSED',
timeSeries:'Time series',ownership:'Ownership / dependency',components:'Components / metric families',metricExplorer:'Metric explorer',sourceBrowser:'Source browser',officialSource:'Official source',
candidates:'Candidates',threads:'Investigation threads',evidenceGraph:'Evidence graph',source:'Source',entity:'Entity',semantic:'Semantics',lineage:'Lineage',decisions:'Time-series decisions',
implemented:'Actually implemented capabilities',publicStatic:'Public static',localFull:'Local full'
}};
const t=k=>I18N[state.lang][k]||k;
async function api(p,opts){const r=await fetch(p,opts);if(!r.ok)throw new Error(await r.text());return r.json()}
async function loadSnapshot(){if(window.FI2A_PUBLIC_SNAPSHOT)return window.FI2A_PUBLIC_SNAPSHOT;return api('/api/snapshot')}
function setLang(lang){state.lang=lang;document.documentElement.lang=lang;$$('[data-i18n]').forEach(el=>{el.textContent=t(el.dataset.i18n)});renderGates();renderMetrics();renderEntityBrowser();if(state.snapshot){runAsk();runInvestigate();runDiscover();if($('#searchQ').value.trim())runSearch()}}
function nameOf(id){return state.entityMap.get(id)?.legal_name||id||'—'}
function metricOf(code){return state.metricMap.get(code)||{code,name:code,families:[]}}
function sourceOf(id){return state.sourceMap.get(id)||null}
function val(o){if(!o)return'—';if(o.numeric_value_real!=null){const u=String(o.unit||'');if(u.toLowerCase()==='ratio')return`${fmt(Number(o.numeric_value_real)*100)} %`;if(u==='PERCENT')return`${fmt(o.numeric_value_real)} %`;return`${fmt(o.numeric_value_real)} ${esc(u)}`.trim()}return esc(o.text_value||o.numeric_value_text||'—')}
function badge(s,c=''){return`<span class="badge ${c}">${esc(s)}</span>`}
function sourceLocator(o){if(!o)return t('locatorNotRecorded');const xs=[];if(o.source_page)xs.push(`${t('pageLocator')}: ${o.source_page}`);if(o.source_table)xs.push(`${t('tableLocator')}: ${o.source_table}`);if(o.source_datapoint)xs.push(`${t('datapointLocator')}: ${o.source_datapoint}`);return xs.length?xs.join(' · '):t('locatorNotRecorded')}
function sourceLine(o){const s=sourceOf(o?.source_id);return s?`${esc(s.publisher||'')} · ${esc(s.title||'')} · ${esc(sourceLocator(o))}`:'—'}
function factCard(o){if(!o)return`<div class="empty">${t('noFact')}</div>`;const m=metricOf(o.metric_code),s=o.semantic||{},scope=o.consolidation_scope||s.consolidation_scope||t('notRecorded');return`<article class="card fact"><div class="eyebrow">${esc(o.epistemic_class||'FACT')}</div><h4>${esc(nameOf(o.entity_id))}</h4><div class="big">${val(o)}</div><div>${esc(m.name||m.code)}</div><div class="badges">${badge(o.reference_date||t('notRecorded'))}${badge(s.reporting_framework||'UNRESOLVED')}${badge(scope)}${o.uncertain?badge('UNCERTAIN','warn'):''}</div><div class="source-line">${sourceLine(o)}</div><button class="mini audit-link" data-id="${esc(o.id)}">${t('auditButton')}</button></article>`}
function regimes(eid){return state.snapshot.regime_memberships.filter(x=>x.entity_id===eid&&String(x.status||'').startsWith('ACTIVE')).map(x=>x.regime_code)}
function latest(eid,mc){const xs=state.snapshot.observations.filter(o=>o.entity_id===eid&&o.metric_code===mc).sort((a,b)=>(a.reference_date||'').localeCompare(b.reference_date||''));return xs.at(-1)||null}
function entityMetrics(eid){return[...new Set(state.snapshot.observations.filter(o=>o.entity_id===eid).map(o=>o.metric_code))].sort()}
function dossierHtml(eid){const e=state.entityMap.get(eid),obs=state.snapshot.observations.filter(o=>o.entity_id===eid),src=new Set(obs.map(o=>o.source_id)),rel=state.snapshot.relations.filter(r=>r.subject_entity_id===eid||r.object_entity_id===eid),periods=[...new Set(obs.map(o=>o.reference_date).filter(Boolean))].sort();return`<div class="dossier"><h4>${esc(e?.legal_name||eid)}</h4><div class="kv"><span>${t('type')}</span><b>${esc(e?.type||'—')}</b><span>${t('country')}</span><b>${esc(e?.country||'—')}</b><span>${t('regimes')}</span><b>${esc(regimes(eid).join(', ')||'—')}</b><span>${t('facts')}</span><b>${obs.length}</b><span>${t('sources')}</span><b>${src.size}</b><span>${t('relations')}</span><b>${rel.length}</b><span>${t('periods')}</span><b>${periods[0]||'—'} → ${periods.at(-1)||'—'}</b></div></div>`}
function renderGates(){if(!state.snapshot)return;const g=state.snapshot.meta.release_gates||{};$('#gateCard').innerHTML=`<div class="gate-title">${t('releaseGates')}</div>${['PUBLIC_RELEASE','RAW_SOURCE_REDISTRIBUTION','AUTONOMOUS_LLM_HYPOTHESIS','INSURANCE_PEER_DISCOVERY'].map(k=>`<div class="gate-row"><span>${esc(k)}</span><b class="${String(g[k]||'').startsWith('OPEN')?'ok':''}">${esc(g[k]||'—')}</b></div>`).join('')}<div class="gate-row"><span>${t('runtime')}</span><b class="ok">${state.runtime==='static'?t('static'):t('local')}</b></div><p class="gate-help">${esc(t('autonomousGateHelp'))}</p>`}
function renderMetrics(){if(!state.snapshot)return;const c=state.snapshot.meta.counts;$('#metrics').innerHTML=[[c.entities,t('institution')],[c.metrics,t('metric')],[c.observations,t('facts')],[c.sources,t('sources')],[c.time_series_decisions,t('decisions')]].map(([v,l])=>`<div class="metric"><strong>${fmt(v)}</strong><span>${esc(l)}</span></div>`).join('')}
function fillSelect(sel,items,value,text,blank=false){const cur=sel.value;sel.innerHTML=(blank?'<option value="">—</option>':'')+items.map(x=>`<option value="${esc(value(x))}">${esc(text(x))}</option>`).join('');if([...sel.options].some(o=>o.value===cur))sel.value=cur}
function bindAuditLinks(){$$('.audit-link').forEach(b=>b.onclick=()=>{showMode('audit');$('#auditId').value=b.dataset.id;runAudit()})}
function showMode(mode){$$('.mode').forEach(x=>x.classList.toggle('active',x.id===`mode-${mode}`));$$('#modeTabs button').forEach(x=>x.classList.toggle('active',x.dataset.mode===mode))}
function evidenceSearchLocal(q,limit=50){const toks=String(q||'').toLocaleLowerCase().split(/\s+/).filter(x=>x.length>=2),res=[];if(!toks.length)return[];for(const o of state.snapshot.observations){const e=state.entityMap.get(o.entity_id)||{},m=metricOf(o.metric_code),s=sourceOf(o.source_id)||{};const txt=[e.legal_name,e.country,e.type,m.code,m.name,m.definition,(m.families||[]).join(' '),s.publisher,s.title,s.source_family,o.text_value,o.numeric_value_text,o.source_raw_value,o.reference_date,o.epistemic_class].join(' ').toLocaleLowerCase();if(toks.every(x=>txt.includes(x))){let score=0;toks.forEach(x=>{if(String(e.legal_name||'').toLocaleLowerCase().includes(x))score+=8;if(String(m.name||'').toLocaleLowerCase().includes(x)||String(m.code||'').toLocaleLowerCase().includes(x))score+=7;if(String(s.title||'').toLocaleLowerCase().includes(x))score+=7;if(String(s.publisher||'').toLocaleLowerCase().includes(x))score+=5;score+=1});res.push({score,observation:o})}}return res.sort((a,b)=>b.score-a.score).slice(0,limit)}
async function runSearch(){const q=$('#searchQ').value.trim();if(!q){$('#searchResult').innerHTML=`<div class="empty">${t('enterSearch')}</div>`;return}let rows;if(state.runtime==='local'){const r=await api('/api/search?q='+encodeURIComponent(q)+'&limit=50');rows=r.results.map(x=>({score:x.score,observation:x.observation}))}else rows=evidenceSearchLocal(q);$('#searchResult').innerHTML=rows.length?`<div class="card-grid">${rows.map(x=>factCard(x.observation)).join('')}</div>`:`<div class="empty">${t('noResults')}</div>`;bindAuditLinks()}
function renderEntityBrowser(){if(!state.snapshot)return;const q=($('#entityFilter')?.value||'').toLocaleLowerCase(),ty=$('#entityTypeFilter')?.value||'',co=$('#entityCountryFilter')?.value||'';const rows=state.snapshot.entities.filter(e=>(!q||String(e.legal_name||'').toLocaleLowerCase().includes(q))&&(!ty||e.type===ty)&&(!co||e.country===co)).slice(0,250);$('#entityBrowser').innerHTML=`<div class="browser-grid">${rows.map(e=>`<button class="browser-row" data-eid="${esc(e.id)}"><b>${esc(e.legal_name)}</b><span>${esc(e.type||'')} · ${esc(e.country||'')}</span><small>${esc(regimes(e.id).join(', '))}</small></button>`).join('')}</div>`;$$('.browser-row').forEach(b=>b.onclick=()=>{$('#askEntity').value=b.dataset.eid;syncEntityMetric('ask');runAsk()})}
function syncEntityMetric(prefix){const eid=$('#'+prefix+'Entity').value,sel=$('#'+prefix+'Metric'),codes=entityMetrics(eid),items=codes.map(c=>metricOf(c));fillSelect(sel,items,x=>x.code,x=>`${x.name||x.code} · ${x.code}`)}
function runAsk(){const eid=$('#askEntity').value,mc=$('#askMetric').value;$('#askResult').innerHTML=dossierHtml(eid)+`<div class="card-grid">${factCard(latest(eid,mc))}</div>`;bindAuditLinks()}
function compareLocal(mc,ids){const obs=ids.map(id=>latest(id,mc)),pairs=[];let status='EXACTLY_COMPARABLE';const rank={EXACTLY_COMPARABLE:0,APPROXIMATE_ONLY:1,UNRESOLVED:2,NOT_COMPARABLE:3};const cls=(a,b)=>{if(!a||!b)return{status:'UNRESOLVED',reasons:['MISSING_OBSERVATION']};const reasons=[];if(a.unit!==b.unit)reasons.push('UNIT_MISMATCH');if((a.currency||'')!==(b.currency||''))reasons.push('CURRENCY_MISMATCH');const sa=a.semantic||{},sb=b.semantic||{};if((sa.reporting_framework||'')!==(sb.reporting_framework||''))reasons.push('FRAMEWORK_MISMATCH');if((sa.semantic_fingerprint||'')!==(sb.semantic_fingerprint||''))reasons.push('SEMANTIC_FINGERPRINT_DIFFERS');const ra=regimes(a.entity_id).sort().join('|'),rb=regimes(b.entity_id).sort().join('|');if(ra&&rb&&ra!==rb)reasons.push('REGIME_MISMATCH');if(reasons.some(x=>/UNIT|CURRENCY|REGIME/.test(x)))return{status:'NOT_COMPARABLE',reasons};return reasons.length?{status:'APPROXIMATE_ONLY',reasons}:{status:'EXACTLY_COMPARABLE',reasons:[]}};for(let i=0;i<obs.length;i++)for(let j=i+1;j<obs.length;j++){const c=cls(obs[i],obs[j]);pairs.push({a:ids[i],b:ids[j],...c});if(rank[c.status]>rank[status])status=c.status}const parent=new Map(ids.map(x=>[x,x])),find=x=>{let p=parent.get(x)||x;while(p!==(parent.get(p)||p)){parent.set(p,parent.get(parent.get(p)));p=parent.get(p)}return p},union=(a,b)=>{if(!parent.has(a)||!parent.has(b))return;const x=find(a),y=find(b);if(x!==y)parent.set(y,x)};state.snapshot.relations.filter(r=>r.dependency_relevant&&String(r.status||'').startsWith('ACTIVE')).forEach(r=>union(r.subject_entity_id,r.object_entity_id));const valid=obs.map((o,i)=>[o,ids[i]]).filter(([o])=>o&&o.numeric_value_real!=null),groups=new Set(valid.map(([o,id])=>find(id))),statsOK=status==='EXACTLY_COMPARABLE'&&valid.length>=5&&groups.size===valid.length;let statistics=null;if(statsOK){const vals=valid.map(([o])=>Number(o.numeric_value_real)).sort((a,b)=>a-b),median=a=>{const n=a.length,m=Math.floor(n/2);return n%2?a[m]:(a[m-1]+a[m])/2},med=median(vals),mad=median(vals.map(v=>Math.abs(v-med)).sort((a,b)=>a-b));statistics={n:vals.length,median:med,mad,dependency_aware:true,rows:valid.map(([o,id])=>({entity_id:id,value:Number(o.numeric_value_real),robust_z:mad?0.67448975*(Number(o.numeric_value_real)-med)/mad:null}))}}return{observations:obs,pairwise:pairs,overall_status:status,statistics_authorized:statsOK,statistics,ranking_authorized:false}}
async function runCompare(ids){const mc=$('#cmpMetric').value,r=state.runtime==='local'?await api('/api/compare',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({metric_code:mc,entity_ids:ids})}):compareLocal(mc,ids);$('#compareResult').innerHTML=`<div class="compare-status">${badge(r.overall_status,r.overall_status==='EXACTLY_COMPARABLE'?'good':r.overall_status==='NOT_COMPARABLE'?'bad':'warn')} ${r.statistics_authorized?badge(t('statisticsAuthorized'),'good'):badge(t('statisticsWithheld'),'warn')} ${badge(t('rankingClosed'),'bad')}</div><div class="card-grid">${(r.observations||[]).map(factCard).join('')}</div><div class="pair-list">${(r.pairwise||[]).map(p=>`<div><b>${esc(nameOf(p.a))} ↔ ${esc(nameOf(p.b))}</b>${badge(p.status)}<small>${esc((p.reasons||[]).join(', '))}</small></div>`).join('')}</div>${r.statistics?`<pre>${esc(JSON.stringify(r.statistics,null,2))}</pre>`:''}`;bindAuditLinks()}
function svgSeries(xs){const ys=xs.filter(o=>o.numeric_value_real!=null);if(ys.length<2)return`<div class="empty">${t('noResults')}</div>`;const W=760,H=230,p=30,min=Math.min(...ys.map(o=>Number(o.numeric_value_real))),max=Math.max(...ys.map(o=>Number(o.numeric_value_real))),span=max-min||1,pts=ys.map((o,i)=>[p+i*(W-2*p)/(ys.length-1),H-p-(Number(o.numeric_value_real)-min)*(H-2*p)/span,o]),path=pts.map((x,i)=>(i?'L':'M')+x[0].toFixed(1)+','+x[1].toFixed(1)).join(' ');return`<svg viewBox="0 0 ${W} ${H}" class="chart"><path d="${path}" fill="none" stroke="currentColor" stroke-width="3"/>${pts.map(x=>`<circle cx="${x[0]}" cy="${x[1]}" r="4"><title>${esc(x[2].reference_date)} · ${fmt(x[2].numeric_value_real)}</title></circle>`).join('')}</svg><div class="series-table">${ys.map(o=>`<div><span>${esc(o.reference_date)}</span><b>${val(o)}</b><small>${esc(o.restatement_version||'')}</small></div>`).join('')}</div>`}
function connectedRelations(eid){const rel=state.snapshot.relations.filter(r=>String(r.status||'').startsWith('ACTIVE')),adj=new Map();rel.forEach(r=>{if(!adj.has(r.subject_entity_id))adj.set(r.subject_entity_id,new Set());if(!adj.has(r.object_entity_id))adj.set(r.object_entity_id,new Set());adj.get(r.subject_entity_id).add(r.object_entity_id);adj.get(r.object_entity_id).add(r.subject_entity_id)});const seen=new Set([eid]),stack=[eid];while(stack.length){const x=stack.pop();for(const y of adj.get(x)||[])if(!seen.has(y)){seen.add(y);stack.push(y)}}return rel.filter(r=>seen.has(r.subject_entity_id)&&seen.has(r.object_entity_id))}
function ownershipSvg(eid){const rel=connectedRelations(eid);if(!rel.length)return`<div class="empty">${t('noResults')}</div>`;const nodes=[...new Set(rel.flatMap(r=>[r.subject_entity_id,r.object_entity_id]))],W=760,H=Math.max(240,nodes.length*65),pos=new Map(nodes.map((n,i)=>[n,[i%2?520:150,55+i*55]]));return`<svg viewBox="0 0 ${W} ${H}" class="graph">${rel.map(r=>{const a=pos.get(r.subject_entity_id),b=pos.get(r.object_entity_id);return`<line x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}"/><text x="${(a[0]+b[0])/2}" y="${(a[1]+b[1])/2-5}">${esc(r.relation_type)}${r.ownership_percent!=null?' '+fmt(r.ownership_percent)+'%':''}</text>`}).join('')}${nodes.map(n=>{const p=pos.get(n);return`<circle cx="${p[0]}" cy="${p[1]}" r="8"/><text x="${p[0]+14}" y="${p[1]+4}">${esc(nameOf(n))}</text>`}).join('')}</svg>`}
function componentHtml(eid){const obs=state.snapshot.observations.filter(o=>o.entity_id===eid),groups={};obs.forEach(o=>(metricOf(o.metric_code).families||['UNCLASSIFIED']).forEach(f=>{groups[f]??={};groups[f][o.metric_code]??=[];groups[f][o.metric_code].push(o)}));return Object.keys(groups).sort().map(f=>`<details><summary>${esc(f)} · ${Object.keys(groups[f]).length}</summary>${Object.entries(groups[f]).sort().map(([mc,xs])=>{xs.sort((a,b)=>(a.reference_date||'').localeCompare(b.reference_date||''));return`<div class="component-row"><b>${esc(metricOf(mc).name||mc)}</b><span>${val(xs.at(-1))}</span><small>${esc(xs[0]?.reference_date||'')} → ${esc(xs.at(-1)?.reference_date||'')}</small></div>`}).join('')}</details>`).join('')||`<div class="empty">${t('noResults')}</div>`}
function metricHtml(mc){const m=metricOf(mc),xs=state.snapshot.observations.filter(o=>o.metric_code===mc),eids=new Set(xs.map(o=>o.entity_id)),periods=[...new Set(xs.map(o=>o.reference_date).filter(Boolean))].sort();return`<article class="card"><h4>${esc(m.name||m.code)}</h4><code>${esc(m.code)}</code><p>${esc(m.definition||'')}</p><div class="badges">${(m.families||[]).map(x=>badge(x)).join('')}</div><div class="kv"><span>${t('institution')}</span><b>${eids.size}</b><span>${t('facts')}</span><b>${xs.length}</b><span>${t('periods')}</span><b>${periods[0]||'—'} → ${periods.at(-1)||'—'}</b></div></article>`}
function runInvestigate(){const eid=$('#invEntity').value,mc=$('#invMetric').value,xs=state.snapshot.observations.filter(o=>o.entity_id===eid&&o.metric_code===mc).sort((a,b)=>(a.reference_date||'').localeCompare(b.reference_date||'')),dec=state.snapshot.time_series_decisions.filter(d=>d.entity_id===eid&&d.metric_code===mc);$('#invDossier').innerHTML=dossierHtml(eid);$('#timeSeries').innerHTML=`<h4>${t('timeSeries')} · ${esc(metricOf(mc).name||mc)}</h4>${svgSeries(xs)}<div class="decision-list">${dec.map(d=>`<div>${badge(d.comparability_status)}<span>${esc(d.period_a)} → ${esc(d.period_b)}</span><small>${esc(JSON.stringify(d.reasons_json||{}))}</small></div>`).join('')}</div>`;$('#ownership').innerHTML=`<h4>${t('ownership')}</h4>${ownershipSvg(eid)}`;$('#componentExplorer').innerHTML=`<h4>${t('components')}</h4>${componentHtml(eid)}`;$('#metricExplorer').innerHTML=`<h4>${t('metricExplorer')}</h4>${metricHtml(mc)}`;const srcs=[...new Set(state.snapshot.observations.filter(o=>o.entity_id===eid).map(o=>o.source_id))].map(sourceOf).filter(Boolean);$('#sourceBrowser').innerHTML=`<h4>${t('sourceBrowser')}</h4><div class="source-grid">${srcs.map(s=>`<article class="card"><b>${esc(s.publisher||'')}</b><div>${esc(s.title||'')}</div><small>${esc(s.source_family||'')} · ${esc(s.publication_date||'')}</small><code>${esc(s.sha256||'')}</code>${s.url?`<a href="${esc(s.url)}" target="_blank" rel="noopener">${t('officialSource')}</a>`:''}</article>`).join('')}</div>`}
function runDiscover(){const eid=$('#discEntity').value,cands=(state.snapshot.generated_discovery_candidates||[]).filter(c=>!eid||c.entity_id===eid),threads=state.snapshot.investigation_threads||[];$('#discoverResult').innerHTML=`<h4>${t('candidates')}</h4><div class="candidate-grid">${cands.slice(0,120).map(c=>`<article class="candidate"><div class="eyebrow">${esc(c.kind)}</div>${badge(c.status||'EXPLORATORY_ONLY','warn')}<h4>${esc(c.question||metricOf(c.metric_code||'').name||'Candidate')}</h4><small>${esc(nameOf(c.entity_id))}${c.period_a?' · '+esc(c.period_a)+' → '+esc(c.period_b):''}</small><pre>${esc(JSON.stringify(c.countercheck_plan||c.detail||{},null,2))}</pre></article>`).join('')||`<div class="empty">${t('noResults')}</div>`}</div>`;$('#threadResult').innerHTML=`<h4>${t('threads')}</h4><div class="thread-list">${threads.slice(0,80).map(th=>`<article class="card"><b>${esc(th.title||th.thread_title||th.thread_id||th.id)}</b><small>${esc(th.status||'')}</small><pre>${esc(JSON.stringify(th,null,2))}</pre></article>`).join('')||`<div class="empty">${t('noResults')}</div>`}</div>`}
function graphHtml(g){if(!g||!g.nodes?.length)return`<div class="empty">${t('noResults')}</div>`;return`<h4>${t('evidenceGraph')}</h4><div class="evidence-nodes">${g.nodes.map(n=>`<div class="node ${esc(n.kind.toLowerCase())}"><b>${esc(n.kind)}</b><span>${esc(n.label)}</span></div>`).join('')}</div><div class="edge-list">${g.edges.map(e=>`<div>${esc(e.from)} → <b>${esc(e.type)}</b> → ${esc(e.to)}</div>`).join('')}</div>`}
function evidenceGraphLocal(oid){const o=state.snapshot.observations.find(x=>x.id===oid);if(!o)return null;const nodes=[{id:oid,kind:'OBSERVATION',label:oid}],edges=[],e=state.entityMap.get(o.entity_id),m=metricOf(o.metric_code),s=sourceOf(o.source_id);if(e){nodes.push({id:e.id,kind:'ENTITY',label:e.legal_name});edges.push({from:oid,to:e.id,type:'ABOUT_ENTITY'})}if(m){nodes.push({id:'metric:'+m.code,kind:'METRIC',label:m.name||m.code});edges.push({from:oid,to:'metric:'+m.code,type:'USES_METRIC'})}if(s){nodes.push({id:'source:'+s.id,kind:'SOURCE',label:s.title||s.id});edges.push({from:oid,to:'source:'+s.id,type:'SUPPORTED_BY'})}(state.snapshot.lineage||[]).filter(x=>x.derived_observation_id===oid).forEach(x=>{nodes.push({id:x.input_observation_id,kind:'OBSERVATION',label:x.input_observation_id});edges.push({from:x.input_observation_id,to:oid,type:x.input_role||'INPUT'})});return{nodes,edges}}
async function runAudit(){const id=$('#auditId').value.trim();if(!id)return;let tr,g;if(state.runtime==='local'){[tr,g]=await Promise.all([api('/api/audit/trace?observation_id='+encodeURIComponent(id)),api('/api/audit/graph?observation_id='+encodeURIComponent(id))])}else{const o=state.snapshot.observations.find(x=>x.id===id);if(!o){$('#auditResult').innerHTML=`<div class="empty">${t('noResults')}</div>`;return}tr={observation:o,entity:state.entityMap.get(o.entity_id),metric:metricOf(o.metric_code),source:sourceOf(o.source_id),incoming_lineage:state.snapshot.lineage.filter(x=>x.derived_observation_id===id),outgoing_lineage:state.snapshot.lineage.filter(x=>x.input_observation_id===id),time_series_decisions:state.snapshot.time_series_decisions.filter(x=>x.entity_id===o.entity_id&&x.metric_code===o.metric_code)};g=evidenceGraphLocal(id)}$('#auditResult').innerHTML=`<div class="trace">${factCard(tr.observation)}<article class="card"><h4>${t('entity')}</h4><pre>${esc(JSON.stringify(tr.entity,null,2))}</pre></article><article class="card"><h4>${t('metric')}</h4><pre>${esc(JSON.stringify(tr.metric,null,2))}</pre></article><article class="card"><h4>${t('source')}</h4><pre>${esc(JSON.stringify(tr.source,null,2))}</pre></article><article class="card"><h4>${t('lineage')}</h4><pre>${esc(JSON.stringify({incoming:tr.incoming_lineage,outgoing:tr.outgoing_lineage},null,2))}</pre></article><article class="card"><h4>${t('decisions')}</h4><pre>${esc(JSON.stringify(tr.time_series_decisions,null,2))}</pre></article></div>`;$('#evidenceGraph').innerHTML=graphHtml(g);bindAuditLinks()}
async function runAgent(){if(state.runtime==='static')return;const q=$('#agentQ').value.trim();if(!q)return;const r=await api('/api/agent/query',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q})});$('#agentResult').innerHTML=`<pre>${esc(JSON.stringify(r,null,2))}</pre>`}
async function init(){state.snapshot=await loadSnapshot();state.entityMap=new Map(state.snapshot.entities.map(x=>[x.id,x]));state.metricMap=new Map(state.snapshot.metrics.map(x=>[x.code,x]));state.sourceMap=new Map(state.snapshot.sources.map(x=>[x.id,x]));$('#buildStatus').textContent='READY';if(state.runtime==='static')$$('.local-only').forEach(x=>x.style.display='none');const ents=[...state.snapshot.entities].sort((a,b)=>(a.legal_name||'').localeCompare(b.legal_name||'')),mets=[...state.snapshot.metrics].sort((a,b)=>(a.name||a.code).localeCompare(b.name||b.code));['askEntity','cmpA','cmpB','invEntity'].forEach(id=>fillSelect($('#'+id),ents,x=>x.id,x=>`${x.legal_name} · ${x.type}`));fillSelect($('#discEntity'),ents,x=>x.id,x=>x.legal_name,true);['cmpMetric'].forEach(id=>fillSelect($('#'+id),mets,x=>x.code,x=>`${x.name||x.code} · ${x.code}`));fillSelect($('#cmpCohort'),ents,x=>x.id,x=>x.legal_name);const types=[...new Set(ents.map(e=>e.type).filter(Boolean))].sort(),countries=[...new Set(ents.map(e=>e.country).filter(Boolean))].sort();fillSelect($('#entityTypeFilter'),types,x=>x,x=>x,true);fillSelect($('#entityCountryFilter'),countries,x=>x,x=>x,true);const first=ents[0]?.id;if(first){$('#askEntity').value=first;$('#invEntity').value=first;syncEntityMetric('ask');syncEntityMetric('inv')}renderMetrics();renderGates();renderEntityBrowser();setLang('de');}
$('#modeTabs').onclick=e=>{if(e.target.dataset.mode)showMode(e.target.dataset.mode)};$('#langToggle').onclick=()=>setLang(state.lang==='de'?'en':'de');$('#askEntity').onchange=()=>{syncEntityMetric('ask');runAsk()};$('#askShow').onclick=runAsk;$('#searchRun').onclick=runSearch;$('#searchQ').onkeydown=e=>{if(e.key==='Enter')runSearch()};$('#entityFilter').oninput=renderEntityBrowser;$('#entityTypeFilter').onchange=renderEntityBrowser;$('#entityCountryFilter').onchange=renderEntityBrowser;$('#cmpRun').onclick=()=>runCompare([$('#cmpA').value,$('#cmpB').value]);$('#cmpCohortRun').onclick=()=>runCompare(Array.from($('#cmpCohort').selectedOptions).map(o=>o.value));$('#invEntity').onchange=()=>{syncEntityMetric('inv');runInvestigate()};$('#invRun').onclick=runInvestigate;$('#discRun').onclick=runDiscover;$('#auditRun').onclick=runAudit;$('#auditRerun').onclick=async()=>{if(state.runtime==='static')return runAudit();const id=$('#auditId').value.trim(),r=await api('/api/rerun',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({operation:'AUDIT_TRACE',observation_id:id})});$('#auditResult').insertAdjacentHTML('afterbegin',`<div class="rerun-ok">RERUN PASS · ${esc(r.result?.observation?.id||'')}</div>`)};$('#agentRun').onclick=runAgent;
init().catch(e=>{$('#buildStatus').textContent='ERROR';document.body.insertAdjacentHTML('beforeend',`<div class="fatal">${esc(e.message)}</div>`);console.error(e)});
